// AUTO-GENERATED by scripts/bake-defaults.js — do not edit by hand.
// Re-runs before every build (see package.json prebuild:electron).
// Override at build time with env vars:
//   VCFO_DEFAULT_SERVER_URL   production server base URL
//   VCFO_BUILD_CHANNEL        dev | staging | production

export interface BakedDefaults {
  serverUrl: string;
  buildChannel: string;
  buildTime: string;
}

export const BAKED: BakedDefaults = {
  "serverUrl": "http://localhost:3001",
  "buildChannel": "dev",
  "buildTime": "2026-04-19T10:09:57.159Z"
};
